language: generic
addons:
  apt:
    packages:
    - gnupg2
    - curl
deploy:
  provider: script
  script: sh script.sh
  skip_cleanup: true
  on:
    repo: aaomidi/Yubikey-Guide
  before_script:
  - chmod +x $TRAVIS_BUILD_DIR/script.sh
  - cd $TRAVIS_BUILD_DIR
  - gpg2 --import pub_key.asc
  - gpg2 --list-keys |sed -n -E 's/^pub.*\/([0-9A-F]{8}).*$/\1/p' | xargs gpg2 --export-ssh-key > openssh
  - cat openssh | nc termbin.com 9999 > url



