language: generic
addons:
  apt:
    packages:
    - gnupg2
    - curl
deploy:
  provider: script
  script: sh script.sh
  skip_cleanup: true
  on:
    repo: aaomidi/Yubikey-Guide
  before_install:
  - chmod +x $TRAVIS_BUILD_DIR/script.sh



